class_name LevelConstants
extends Node

const MOB_TYPES = 4
const PLANE_SIZE = 16.
const LEVEL_SIZE = 160. * PLANE_SIZE
const POINTS_IN_MARGIN_POLYGON = 10
const TOTAL_WIDTH = 60. * PLANE_SIZE
const BRIDGE_WIDTH = 80.
const MAX_MARGIN_WIDTH = (TOTAL_WIDTH - BRIDGE_WIDTH) / 2
const MIN_MARGIN_WIDTH = 2 * PLANE_SIZE
const MARGIN_STABILITY_RATE = 0.6
